export const SIDENAV = "SIDENAV";
export const ASSETS = "ASSETS";
export const INDICATORS = "INDICATORS";
export const UPDATE_INDICATOR = "UPDATE_INDICATOR";
export const DELETE_INDICATOR = "DELETE_INDICATOR";
